services:
  db:
    image: postgres:16-alpine3.18
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=tocos-exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d tocos-exchange -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    # logging:
    #       driver: none       